# Source sheet, can be XLSX or CSV
source_sheet_type: xlsx
# Single or multi accepted.  
source_sheet_count:
# Source_sheet_delimiter is needed only if using CSV.  Can be tab or comma.
source_sheet_delimiter: tab
#Full path to file
source_sheet_file: '/media/sf_VMShare/CRDCSubmissionModel/CRDC_SDM_ACTIVE_TDP.xlsx'
# Path to output directory
output_file_directory: '/media/sf_VMShare/modeltest/'
mappings:
  # In a multi-tab spreadsheet, list all tabs to be ignored
  excluded_tabs:
  - 'notes'
  - 'scratch'
  - 'PDX'
  - 'Input'
  - 'Linkages'
  # Mappings are the column name in the source.  If 'tab' is used for nodes, the xlsx worksheet tab name is used.  Use None to ignore
  #Nodes:  Just need to know the node names
  nodes: 'Node (HC)'
  #Properties:  Need to get property names, CDE ID and version, and required status.  Enums as well.
  properties:
    property_name: 'Property (HC)'
    property_req: 'Required (HC)'
    property_key: 'None'
    property_type: 'None'
    property_description: 'None'
    cde_id: 'CDE (HC)'
    cde_version: 'None'
    enums: 'None'
  # For edges need to have the tab, source column, destination column and cardinality
  edge_info:
    edge_info_source: 'Linkages'
    edge_src: 'Child Node'
    edge_dst: 'Parent Node'
    edge_card: 'Cardinality'
model_info:
  handle: 'CRDC'
  version: '0.0.1'
taginfo:
  nodetags:
    - 'Category': 'Domain (HC)'
  propertytags:
    - 'Template': 'Template (HC)'